### ISSUE TITLE
Unable to run build scripts

### ISSUE THREAD

**Issue by jmickle66666666** [alexey-lysiuk/slade-osx-build#2]
Hi, I've been trying to compile Slade, and was pointed to this repo, but I am unable to run build.sh or xcode.sh because of the following error in prepare.sh (see below)

I am new to working with osx so I'm not sure what the issue here is. I have xcode, git, cmake all installed and up to date. I am using OSX 10.11 El Capitan.

Any ideas?

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:2 (project)


CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
```

**Comment by alexey-lysiuk** [comment]
What are the versions of XCode and CMake?

**Comment by jmickle66666666** [comment]
XCode 8.0 beta, cmake 3.5.2

**Comment by alexey-lysiuk** [comment]
Can't check at the moment but please run Xcode and check Command Line Tools in Location Preference page. CMake cannot find SDK and compiler, most likely command line tools are not installed.

**Comment by jmickle66666666** [comment]
Ah yes, that fixed the C compiler issues. Thanks. I'm still getting SDK issues though, as seen here:

```
-- The C compiler identification is AppleClang 8.0.0.8000033
-- The CXX compiler identification is AppleClang 8.0.0.8000033
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by alexey-lysiuk** [comment]
Have no idea why this happens. I have Xcode 8 on 10.12 only.
The project has been generated without a problem.

Probably some issue with CMake. Xcode 8 contains SDK for 10.12 only and it's higher than your OS version.
I'm using Xcode 7.3.1 on 10.11 and everything works there too.

Anyway, you can try configure from CMake GUI by specifying full path to created `build` directory in **Where to build binaries** edit box.
`CMAKE_OSX_SYSROOT` should be set to `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`

**Comment by jmickle66666666** [comment]
I managed to eventually build an xcode project with cmake GUI just using the slade repo. I have no idea why it isn't working in command line still, searching gave me no conclusive understanding.
